2023-11-22 15:27:52,785 INFO: Microblog startup [in C:\microblog\app\__init__.py:40]
2023-11-22 15:27:58,907 INFO: Microblog startup [in C:\microblog\app\__init__.py:40]
2023-11-22 15:36:53,847 INFO: Microblog startup [in C:\microblog\app\__init__.py:40]
2023-11-22 15:42:27,653 INFO: Microblog startup [in C:\microblog\app\__init__.py:40]
2023-11-22 15:42:35,217 ERROR: Exception on /edit_profile [GET] [in c:\robodk\python37\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "c:\robodk\python37\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\robodk\python37\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\robodk\python37\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\robodk\python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\robodk\python37\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\microblog\app\routes.py", line 89, in edit_profile
    form = EditProfileForm()
  File "c:\robodk\python37\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2023-11-22 15:42:48,395 ERROR: Exception on /edit_profile [GET] [in c:\robodk\python37\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "c:\robodk\python37\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\robodk\python37\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\robodk\python37\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\robodk\python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\robodk\python37\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\microblog\app\routes.py", line 89, in edit_profile
    form = EditProfileForm()
  File "c:\robodk\python37\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2023-11-22 15:43:04,565 ERROR: Exception on /edit_profile [GET] [in c:\robodk\python37\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "c:\robodk\python37\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\robodk\python37\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\robodk\python37\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\robodk\python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\robodk\python37\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\microblog\app\routes.py", line 89, in edit_profile
    form = EditProfileForm()
  File "c:\robodk\python37\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2023-11-22 15:44:06,055 INFO: Microblog startup [in C:\microblog\app\__init__.py:40]
2023-11-22 15:44:15,715 ERROR: Exception on /edit_profile [GET] [in c:\robodk\python37\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "c:\robodk\python37\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\robodk\python37\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\robodk\python37\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\robodk\python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\robodk\python37\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\microblog\app\routes.py", line 89, in edit_profile
    form = EditProfileForm()
  File "c:\robodk\python37\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2023-11-22 15:46:39,671 INFO: Microblog startup [in C:\microblog\app\__init__.py:40]
2023-11-22 15:46:52,133 ERROR: Exception on /edit_profile [GET] [in c:\robodk\python37\lib\site-packages\flask\app.py:1745]
Traceback (most recent call last):
  File "c:\robodk\python37\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\robodk\python37\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\robodk\python37\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\robodk\python37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "c:\robodk\python37\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\microblog\app\routes.py", line 89, in edit_profile
    form = EditProfileForm()
  File "c:\robodk\python37\lib\site-packages\wtforms\form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2023-11-22 15:52:35,243 INFO: Microblog startup [in C:\microblog\app\__init__.py:40]
2023-11-23 14:33:10,601 INFO: Microblog startup [in C:\microblog\app\__init__.py:43]
2023-11-23 14:47:26,170 INFO: Microblog startup [in C:\microblog\app\__init__.py:43]
2023-11-23 15:42:16,685 INFO: Microblog startup [in C:\microblog\app\__init__.py:43]
2023-11-24 14:18:04,840 INFO: Microblog startup [in C:\microblog\app\__init__.py:43]
2023-11-24 14:18:30,531 INFO: Microblog startup [in C:\microblog\app\__init__.py:43]
